# Generated by Django 4.0 on 2021-12-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
